<?php
/**
 * @file
 * Code for the Surveillance Self Defence  feature.
 */

include_once 'ssd_library.features.inc';

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function ssd_library_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_taxonomy_term_view_alter().
 */
function ssd_library_taxonomy_term_view_alter(&$build) {
  if (isset($build['field_synonym'])) {
    if ($build['field_synonym']['#language'] != 'en' && $build['field_synonym']['#language'] != $build['description_field']['#language']) {
      $build['field_synonym']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_taxonomy_term_view_alter().
 */
function ssd_library_page_alter(&$page) {
  $page['content']['system_main']['no_content']['#access'] = FALSE;
}

function ssd_library_glossify_terms_alter(&$terms, $context) {
  uksort($terms, '_sort_by_length');
}

function _sort_by_length($a, $b) {
  if (strlen($a) == strlen($b)) {
    return 0;
  }
  if (strlen($a) < strlen($b)) {
    return 1;
  }
  return -1;
}

/**
 * Implements hook_feedback_presave().
 */
function ssd_library_feedback_presave($entry) {
  // Tag IE6 feedback as processed - it's mostly spam!
  if (strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE 6.0')) {
    $entry->status = FEEDBACK_PROCESSED;
  }
}

/**
 * Implements hook_help().
 */
function ssd_library_help($path, $arg) {
  switch ($path) {
    case 'admin/help#ssd_library':
      // This is here so the site name becomes translatable.
      return t('Surveillance Self-Defense');
  }
}
