<?php
/**
 * @file
 * Code for the Playlist feature.
 */
include_once 'playlist.features.inc';

function playlist_node_view($node) {
  // Include this for access to pathauto_cleanstring().
  require_once(drupal_get_path('module', 'pathauto') . '/pathauto.inc');
  global $language;
  global $base_url;
  
  if ($node->type == 'playlist') {
    /*
    $metatag = array(
      '#type' => 'markup',
      '#tag' => 'meta',
      'attributes' => array(
        'http-equiv' => 'Pragma',
        'content' => 'no-cache',
      ),
      '#weight' => -1000,
    );
    $head = drupal_add_html_head($metatag, 'playlist-no-cache');
    dsm($head);
    
    drupal_add_http_header('Pragma', 'no-cache');
    */
    // Add JS for playlist pages
    $flexslider_path = libraries_get_path('flexslider') . '/jquery.flexslider-min.js';
    $hashchange_path = libraries_get_path('hashchange') . '/jquery.ba-hashchange-min.js';
    $playlist_path = drupal_get_path('module', 'playlist');

    drupal_add_js($flexslider_path);
    drupal_add_js($hashchange_path);
    drupal_add_js($playlist_path . '/js/playlist.js');
    drupal_add_css($playlist_path . '/css/playlist-styles.css');

    // Slide HTML
    $slides = array();
    // Table of Contents HTML
    $toc = '';
    // Slide index, for permlink.
    $index = 1;
    // Get alias for permlink construction.
    $alias = $base_url . '/' . drupal_get_path_alias('node/' . $node->nid);
    // Get modules in the playlist's native language.
    $modules = $node->field_playlist_module[$node->language];
    
    $indexes = array();
    $hashlinks = array(0 => '');
    foreach ($modules as $row) {
      if ($row['access'] == TRUE) {
        $module = node_load($row['nid']);
        
        // @todo Uniquify this - what if same title is used? Blah.
        $module_link = pathauto_cleanstring($module->title);
        $indexes[$module_link] = $index;
        $hashlinks[$index] = $module_link;

        // Construct a permlink.
        $permlink = '<p><a href="' . $alias . '#' . pathauto_cleanstring($module->title) . '">Permlink</a></p>';
        // @bug doesn't use lang context
        // Use the global language to get the right translation. If there is no
        // content for that language, fall back to the playlist node language.
        $body = '';
        if (isset($module->body[$language->language][0]['safe_value'])) {
          $body = $module->body[$language->language][0]['safe_value'];
        }
        else {
          $body = $module->body[$node->language][0]['safe_value'];
        }
        $slides[] = "<h1>{$module->title}</h1>" . $permlink .  $body;
        $toc .= '<li><div class="table-entry-label">Module ' . $index . ':</div> <div class="table-entry-title">' . $module->title . '</li>';
        $index++;
      }
    }
    // Set slides and table of contents so they can be access in the template.
    $node->content['slides'] = $slides;
    $node->content['table-of-contents'] = '<div class="playlist-table"><ul>' . $toc . '</ul></div>';
    
    $settings = array(
      'indexes' => $indexes,
      'hashLinks' => $hashlinks,
    );
    // Pass permlink info to JS.
    drupal_add_js(array('playlist' => $settings), 'setting');
  }
}
