<?php
/**
 * @file
 * Code for the Playlist feature.
 */
include_once 'playlist.features.inc';

function playlist_node_view($node) {
  // Include this for access to pathauto_cleanstring().
  require_once(drupal_get_path('module', 'pathauto') . '/pathauto.inc');
  global $language;
  global $base_url;
  
  if ($node->type == 'playlist') {
    // Add JS for playlist pages
    $flexslider_path = libraries_get_path('flexslider') . '/jquery.flexslider-min.js';
    $hashchange_path = libraries_get_path('hashchange') . '/jquery.ba-hashchange.min.js';
    $playlist_path = drupal_get_path('module', 'playlist');
    drupal_add_js($flexslider_path);
    drupal_add_js($hashchange_path);
    drupal_add_js($playlist_path . '/js/playlist.js');
    drupal_add_css($playlist_path . '/css/playlist-styles.css');

    // Slide HTML
    $slides = array();
    // Table of Contents HTML
    $toc = '';
    // Slide index, for permlink.
    $index = 1;
    // Get alias for permlink construction.
    $alias = $base_url . '/' . $language->language . '/' . drupal_get_path_alias('node/' . $node->nid);
    // Get modules in the playlist's native language.
    $modules = $node->field_playlist_module[$node->language];
    
    $indexes = array();
    $hashlinks = array(0 => 'playlist');
    foreach ($modules as $row) {
      if ($row['access'] == TRUE) {
        $module = node_load($row['nid']);
        
        // @todo Uniquify this - what if same title is used? Blah.
        $module_link = pathauto_cleanstring($module->title);
        $indexes[$module_link] = $index;
        $hashlinks[$index] = $module_link;

        // Construct a permlink.
        $permlink = '<p><a href="' . $alias . '#' . pathauto_cleanstring($module->title) . '">Permlink</a></p>';


        // Render module node for display in playlist.
        $title = $module->title;
        $view = node_view($module, 'full');
        $body = drupal_render($view);
        $slides[] = $body . $permlink;
        $toc .= '<li><div class="table-entry-label">Module ' . $index . ':</div> <div class="table-entry-title">' . $module->title . '</li>';
        $index++;
      }
    }
    // Set slides and table of contents so they can be access in the template.
    $node->content['slides'] = $slides;
    $node->content['playlist_table'] = '<div class="playlist-table"><ul>' . $toc . '</ul></div>';
    
    $settings = array(
      'indexes' => $indexes,
      'hashLinks' => $hashlinks,
    );
    // Pass permlink info to JS.
    drupal_add_js(array('playlist' => $settings), 'setting');
  }
}
