<?php
function glossify_synonyms_glossify_terms_alter(&$terms, $context) {
  // @todo: This module won't work because of overlap between synonyms and terms.
  foreach($terms as $index => $term) {
    $synonym_rs = db_query("
      SELECT field_synonym_value as synonym
      FROM field_data_field_synonym
      WHERE entity_type = 'taxonomy_term' 
      AND entity_id = :term_id 
      AND language = :lang",
    array(':term_id' => $term->id, ':lang' => $context['langcode']));
    
    foreach($synonym_rs as $row) {
      // Get the translations.
      $name = $row->synonym;
      $name_norm = strtolower($name);
      
      // Add another term to the array w/ the translation info.
      $terms[$name_norm] = new stdClass();
      $terms[$name_norm]->name = $name;
      $terms[$name_norm]->name_norm = $name_norm;
      $terms[$name_norm]->id = $term->id;
      $terms[$name_norm]->tip = $term->tip;
      $terms[$name_norm]->format = $term->format;

    }
  }
}
