<?php

/**
 * Implements hook_page_build().
 */
function hreflang_page_build(&$page) {
  $path = drupal_is_front_page() ? '<front>' : $_GET['q'];
  $links = language_negotiation_get_switch_links(LANGUAGE_TYPE_INTERFACE, $path);
  if (empty($links->links)) {
    return;
  }
  foreach ($links->links as $langcode => $link) {
    $attributes = array(
      'href' => url($link['href'], array('absolute' => TRUE, 'language' => $link['language'], 'query' => drupal_get_query_parameters())),
      'rel' => 'alternate',
      'hreflang' => $langcode,
    );
    drupal_add_html_head_link($attributes);
  }
}


